Enable debug logging in CI and make log level configurable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,12 +46,12 @@ jobs:
 
       - name: Run tests
         env:
-          # LITEBASE_TEST_DATA_PATH: /tmp/litebase-test-${{ github.run_id }}-${{ matrix.package.name }}
+          LITEBASE_TEST_DEBUG_LEVEL: debug
           LITEBASE_ROOT_DIRECTORY: ${{ github.workspace }}/
         run: |
           go test . -v
 
-      - name: Cleanup test data
-        if: always()
-        run: |
-          rm -rf /tmp/litebase-test-${{ github.run_id }}-${{ matrix.package.name }} || true
+      # - name: Cleanup test data
+      #   if: always()
+      #   run: |
+      #     rm -rf /tmp/litebase-test-${{ github.run_id }}-${{ matrix.package.name }} || true
